// Code generated by sqlc. DO NOT EDIT.

package storage

import (
	"time"
)

type CollectionJob struct {
	ID                int32
	DistrictShortName string
	SchoolShortName   string
	Url               string
	CreatedAt         time.Time
	UpdtaedAt         time.Time
}

type Count struct {
	Positive        int32
	Symptomatic     int32
	Exposed         int32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	SchoolShortName string
	CountDate       string
}

type District struct {
	Name      string
	ShortName string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type School struct {
	Name              string
	ShortName         string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DistrictShortName string
}
