// Code generated by sqlc. DO NOT EDIT.

package storage

import (
	"time"
)

type Count struct {
	ID          int32
	SchoolID    int32
	Positive    int32
	Symptomatic int32
	Exposed     int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type District struct {
	ID        int32
	Name      string
	ShortName string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type School struct {
	ID         int32
	Name       string
	ShortName  string
	DistrictID int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
